# The port dmo-monitor will use on this computer.
ServerPort: 11235

DBUser: username
DBPass: password
DBPort: 3306
DBName: DBNAME
DBIP: 127.0.0.1

  #### END REQUIRED PARAMS

DmoWrapVersionString: "1.1.0"

  # The number of seconds for the webui to wait before it auto-refreshes itself
  # Default is 0 and means autorefresh is disabled. Min is 10 seconds.
AutoRefreshSeconds: 10

  # The number of seconds a miner can not report in before it is considered late/offline.
  # Minimum is 15 seconds
MinerLateTime: 20

  # The number of days back that you want to show daily stats for. Defaults to 4 if not set.
  # Min is 1, max is 21
DailyStatDays: 5
