  #### REQUIRED PARAMS
  # The port THIS dmo-monitor will use on this computer. 
ServerPort: 11235

  #### END REQUIRED PARAMS

  # The number of seconds for the webui to wait before it auto-refreshes itself
  # Default is 0 and means autorefresh is disabled.
AutoRefreshSeconds: 5


  # The number of seconds a miner can not report in before it is considered late/offline.
  # Minimum is 15 seconds
MinerLateTime: 15

  # The number of days back that you want to show daily stats for. Defaults to 4 if not set.
  # Min is 1, max is 21
DailyStatDays: 5

  # Used to send notifications when your miners go offline via telegram
  # You will need to put YOUR telegram user id here AND you will need to /start a conversation with @dmo_monitor_bot
  # Leave this blank if you do not want to set this up
  # This line will look like this if you add your user id: TelegramUserId: 34532453252
  # To get your user id from telegram, just send a message to @userinfobot
TelegramUserId:  

  #### Wallet Stats Config Options
  # These options are for displaying wallet mining stats and are only currently valid for solo mining
  # If you are not solo mining, or don't care about this, you can leave this section unchanged

  # Your full node ip, this is where your miners are also mining to
NodeIP: XXX.XXX.XXX.XXX
  # Your full node port, the same as used by your miners
NodePort: 6434
  # Your full node username and password
NodeUser: someusername
NodePass: somepassword
  # These should be wallet NAMES, not receiving addresses, comma separated. 
  # The wallets named here should be wallets that are available on this fullnode
  # You must populate this with at least one wallet name if you want to use the Wallet Stats
WalletsToMonitor: MyExampleWalletName1,MyExampleWalletName2
  #### End Wallet Stats Config Options
